[package]
name = "final_proj"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
ndarray = "0.15"
ndarray-rand = "0.14"
rand = "0.8"


